version: '3.7'
services:
  postgres:
    container_name: postgresql_dbMIO
    build: 
      context: ./Docker
      dockerfile: db.dockerfile 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lso
      TZ: 'Europe/Rome'
      PGTZ: 'Europe/Rome'
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      app_net:
        ipv4_address: 192.168.0.2


  pgadmin:
    container_name: pgadmin4MIO
    image: dpage/pgadmin4:6.17
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      # PGADMIN_LISTEN_PORT=80
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3


networks:
  app_net:
    ipam:
      driver: default
      config:
      - subnet: "192.168.0.0/24"
        gateway: 192.168.0.1